from django.urls import path

from .views import (
    AdminAsteriskImportPreviewView,
    AdminAsteriskImportSelectedPreviewView,
    AdminAsteriskImportSelectedView,
    AdminAsteriskImportView,
    AdminAsteriskHealthView,
    AdminAsteriskInspectView,
    AdminAsteriskInventoryView,
    AdminLocationArchiveView,
    AdminLocationListCreateView,
    AdminLocationRestoreView,
    AdminScheduleSyncJobListView,
    AdminScheduleSyncJobProcessView,
    AdminTenantListCreateView,
    CallCenterLocationListView,
    CurrentUserView,
    CsrfCookieView,
    LoginView,
    LogoutView,
    OperationSchedulePreviewView,
    OperationScheduleAsteriskComparisonView,
    OperationScheduleRefreshFromAsteriskView,
    OperationScheduleUpdateView,
    ScheduleChangeLogListView,
)


urlpatterns = [
    path(
        "auth/csrf/",
        CsrfCookieView.as_view(),
        name="auth-csrf",
    ),
    path(
        "auth/login/",
        LoginView.as_view(),
        name="auth-login",
    ),
    path(
        "auth/logout/",
        LogoutView.as_view(),
        name="auth-logout",
    ),
    path(
        "me/",
        CurrentUserView.as_view(),
        name="current-user",
    ),
    path(
        "locations/",
        CallCenterLocationListView.as_view(),
        name="callcenter-location-list",
    ),
    path(
        "locations/<int:location_id>/schedule/",
        OperationScheduleUpdateView.as_view(),
        name="operation-schedule-update",
    ),
    path(
        "locations/<int:location_id>/schedule/preview/",
        OperationSchedulePreviewView.as_view(),
        name="operation-schedule-preview",
    ),
    path(
        "locations/<int:location_id>/schedule/refresh-from-asterisk/",
        OperationScheduleRefreshFromAsteriskView.as_view(),
        name="operation-schedule-refresh-from-asterisk",
    ),
    path(
        "locations/<int:location_id>/schedule/compare-asterisk/",
        OperationScheduleAsteriskComparisonView.as_view(),
        name="operation-schedule-compare-asterisk",
    ),
    path(
        "locations/<int:location_id>/schedule-changes/",
        ScheduleChangeLogListView.as_view(),
        name="schedule-change-log-list",
    ),
    path(
        "admin/tenants/",
        AdminTenantListCreateView.as_view(),
        name="admin-tenant-list-create",
    ),
    path(
        "admin/locations/",
        AdminLocationListCreateView.as_view(),
        name="admin-location-list-create",
    ),
    path(
        "admin/locations/<int:location_id>/archive/",
        AdminLocationArchiveView.as_view(),
        name="admin-location-archive",
    ),
    path(
        "admin/locations/<int:location_id>/restore/",
        AdminLocationRestoreView.as_view(),
        name="admin-location-restore",
    ),
    path(
        "admin/asterisk/inspect/",
        AdminAsteriskInspectView.as_view(),
        name="admin-asterisk-inspect",
    ),
    path(
        "admin/asterisk/inventory/",
        AdminAsteriskInventoryView.as_view(),
        name="admin-asterisk-inventory",
    ),
    path(
        "admin/asterisk/health/",
        AdminAsteriskHealthView.as_view(),
        name="admin-asterisk-health",
    ),
    path(
        "admin/asterisk/import-preview/",
        AdminAsteriskImportPreviewView.as_view(),
        name="admin-asterisk-import-preview",
    ),
    path(
        "admin/asterisk/import-selected-preview/",
        AdminAsteriskImportSelectedPreviewView.as_view(),
        name="admin-asterisk-import-selected-preview",
    ),
    path(
        "admin/asterisk/import/",
        AdminAsteriskImportView.as_view(),
        name="admin-asterisk-import",
    ),
    path(
        "admin/asterisk/import-selected/",
        AdminAsteriskImportSelectedView.as_view(),
        name="admin-asterisk-import-selected",
    ),
    path(
        "admin/sync-jobs/",
        AdminScheduleSyncJobListView.as_view(),
        name="admin-schedule-sync-job-list",
    ),
    path(
        "admin/sync-jobs/process/",
        AdminScheduleSyncJobProcessView.as_view(),
        name="admin-schedule-sync-job-process",
    ),
]
