from django.urls import path

from .views import (
    AdminAsteriskImportPreviewView,
    AdminAsteriskImportView,
    AdminAsteriskInspectView,
    AdminLocationListCreateView,
    AdminScheduleSyncJobListView,
    AdminScheduleSyncJobProcessView,
    AdminTenantListCreateView,
    CallCenterLocationListView,
    CurrentUserView,
    CsrfCookieView,
    LoginView,
    LogoutView,
    OperationSchedulePreviewView,
    OperationScheduleUpdateView,
    ScheduleChangeLogListView,
)


urlpatterns = [
    path(
        "auth/csrf/",
        CsrfCookieView.as_view(),
        name="auth-csrf",
    ),
    path(
        "auth/login/",
        LoginView.as_view(),
        name="auth-login",
    ),
    path(
        "auth/logout/",
        LogoutView.as_view(),
        name="auth-logout",
    ),
    path(
        "me/",
        CurrentUserView.as_view(),
        name="current-user",
    ),
    path(
        "locations/",
        CallCenterLocationListView.as_view(),
        name="callcenter-location-list",
    ),
    path(
        "locations/<int:location_id>/schedule/",
        OperationScheduleUpdateView.as_view(),
        name="operation-schedule-update",
    ),
    path(
        "locations/<int:location_id>/schedule/preview/",
        OperationSchedulePreviewView.as_view(),
        name="operation-schedule-preview",
    ),
    path(
        "locations/<int:location_id>/schedule-changes/",
        ScheduleChangeLogListView.as_view(),
        name="schedule-change-log-list",
    ),
    path(
        "admin/tenants/",
        AdminTenantListCreateView.as_view(),
        name="admin-tenant-list-create",
    ),
    path(
        "admin/locations/",
        AdminLocationListCreateView.as_view(),
        name="admin-location-list-create",
    ),
    path(
        "admin/asterisk/inspect/",
        AdminAsteriskInspectView.as_view(),
        name="admin-asterisk-inspect",
    ),
    path(
        "admin/asterisk/import-preview/",
        AdminAsteriskImportPreviewView.as_view(),
        name="admin-asterisk-import-preview",
    ),
    path(
        "admin/asterisk/import/",
        AdminAsteriskImportView.as_view(),
        name="admin-asterisk-import",
    ),
    path(
        "admin/sync-jobs/",
        AdminScheduleSyncJobListView.as_view(),
        name="admin-schedule-sync-job-list",
    ),
    path(
        "admin/sync-jobs/process/",
        AdminScheduleSyncJobProcessView.as_view(),
        name="admin-schedule-sync-job-process",
    ),
]
