# Generated by Django 6.0.6 on 2026-06-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100)),
                ('astdb_family', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operation_schedule', to='control_horarios.callcenterlocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_schedules', to='control_horarios.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'location__name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('before_value', models.JSONField(default=dict)),
                ('after_value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_changes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_change_logs', to='control_horarios.callcenterlocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_change_logs', to='control_horarios.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='callcenterlocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='control_horarios.tenant'),
        ),
        migrations.CreateModel(
            name='OperationScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Lunes'), ('Tue', 'Martes'), ('Wed', 'Miercoles'), ('Thu', 'Jueves'), ('Fri', 'Viernes'), ('Sat', 'Sabado'), ('Sun', 'Domingo')], max_length=3)),
                ('ranges', models.JSONField(blank=True, default=list)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='control_horarios.operationschedule')),
            ],
            options={
                'ordering': ['schedule', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'day_of_week'), name='unique_day_per_schedule')],
            },
        ),
        migrations.AddConstraint(
            model_name='callcenterlocation',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_location_code_per_tenant'),
        ),
    ]
