# Generated by Django 6.0.6 on 2026-06-23 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horarios', '0002_tenantmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationschedule',
            name='last_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationschedule',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationschedule',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduleSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='control_horarios.schedulechangelog')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_sync_jobs', to='control_horarios.callcenterlocation')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_schedule_sync_jobs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='control_horarios.operationschedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_sync_jobs', to='control_horarios.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='control_hor_status_c715b8_idx'), models.Index(fields=['location', 'status'], name='control_hor_locatio_504394_idx')],
            },
        ),
    ]
