# Generated by Django 6.0.6 on 2026-06-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horarios', '0003_operationschedule_last_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcenterlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
